#!/usr/bin/env python3
"""生成杭州中文标题，合并进 tools/titles_zh.json。克制直译：
- 贴着英文原文，不添加原文没有的推断
- 无法确证的音译代号（Paidle/Telar/Pusiang/Laige...）保留英文原样
- 人名保留英文原样
- 同名重复加 之一/之二 区分
"""
import json, collections

S = "/private/tmp/claude-501/-Users-jinbin-Documents-codeup-china-old-photos/c523ad1d-be82-4051-9d25-c8fff0111da4/scratchpad"
BASE = "/Users/jinbin/Documents/codeup/china-old-photos"

# 无题幻灯片：依画面给最简描述
UNTITLED = {
 "0281": "无题幻灯片·湖畔亭台", "0282": "无题幻灯片·编竹器的匠人",
 "0283": "无题幻灯片·商铺街道", "0285": "无题幻灯片·操大刀的匠人",
 "0286": "无题幻灯片·织机作坊", "0287": "无题幻灯片·织机前的工人",
 "0288": "无题幻灯片·大陶壶与孩童", "0290": "无题幻灯片·持弓形工具的匠人",
 "0292": "无题幻灯片·课桌前的学童", "0293": "无题幻灯片·作坊中的匠人",
 "0295": "无题幻灯片·学童列队合影", "0296": "无题幻灯片·河边玩水的孩童",
 "0298": "无题幻灯片·水中的水牛", "0299": "无题幻灯片·河岸停泊的篷船",
 "0301": "无题幻灯片·街上成堆的竹子", "0302": "无题幻灯片·河边晾晒的染布",
 "0303": "无题幻灯片·河上摇橹的船", "0304": "无题幻灯片·桥洞下望",
 "0306": "无题幻灯片·抱着孩子的乞妇", "0309": "无题幻灯片·堆满木料的巷子",
 "0310": "无题幻灯片·作坊里的男童", "0368": "无题幻灯片·院中游戏的孩童",
 "0369": "无题幻灯片·女童列队合影", "0386": "无题幻灯片·案前进食的男子",
 "0478": "无题幻灯片·制伞",
}

T = {
 "Hangchow - Burning opium": "杭州·焚烧鸦片",
 "Hangchow- Watching Foreigners": "杭州·围看外国人",
 "Bridge over Canal in city": "城内运河上的桥",
 "Bridge": "桥",
 "Buddha in mountain": "山中佛像",
 "Buddha statue in mountain": "山中佛像",
 "Children West and East": "中西儿童",
 "Group of children some carrying leveler, dogs sleeping": "孩童群像，有人提着水准器，卧狗",
 "Family at table": "一家人围桌",
 "Family": "一家人",
 "Fishing with net from dockside": "码头边撒网捕鱼",
 "Gate": "门",
 "3 Chinese men (conversing)": "三名中国男子（交谈）",
 "3 Chinese men (standing)": "三名中国男子（站立）",
 "Group portrait (Chinese men)": "群像（中国男子）",
 "Sawing logs, 2-men saw": "双人锯木",
 "Seated man surrounded by baskets": "坐在竹篮间的男子",
 "Shrine (for carrying?)": "神龛（供抬行？）",
 "Soldiers with flag": "持旗士兵",
 "Children holding hands": "手牵手的孩童",
 "BOW street scene": "BOW·街景",
 "BOW line of men holding ropes and stocks": "BOW·持绳与木枷的队列",
 "Sidney Gamble with camera on boat deck and in another handwriting style SDG w camera 1908":
   "甘博持相机立于船板（另一笔迹：SDG w camera 1908）",
 "Sedan chair (Western man and in another handwriting style David B. Gamble 1908)":
   "轿子（西方男子；另一笔迹：David B. Gamble 1908）",
 "wheelbarrow with Sidney and Clarence Gamble 1908": "独轮车与 Sidney、Clarence Gamble 1908",
 "Group of Boys": "男童群像",
 "Temple China [1908]": "寺庙 [1908]",
 "Street Market [China, 1908]": "街市 [1908]",
 "Chinese Children [1908]": "中国孩童 [1908]",
 "Street Scene [1908]": "街景 [1908]",
 "Temple Interior [1908]": "寺庙内景 [1908]",
 "Temple interior": "寺庙内景",
 "Chinese Prisoner in Stocks [1908]": "戴木枷的囚犯 [1908]",
 "Drawing of a monkey [1908]": "猴的画像 [1908]",
 "Drawing of a lion": "狮的画像",
 "Two Western Women in Sedan Chairs [1908]": "两名西方女子乘轿 [1908]",
 "Robert Ftich and Family [1908]": "Robert Fitch 一家 [1908]",
 "Temple on Hill": "山上的寺庙",
 "Western man riding in hand-pulled cart China [1908]": "西方男子乘人力车 [1908]",
 "Western girl beside carriage [1908]": "马车旁的西方女孩 [1908]",
 "Western girl beside carriage": "马车旁的西方女孩",
 "Fortune teller at table [1908]": "桌前的算命人 [1908]",
 "Chinese fortune teller sitting next to a table [1908]": "桌边的中国算命人 [1908]",
 "Pagoda [1908]": "塔 [1908]",
 "children on street": "街上的孩童",
 "Children on street": "街上的孩童",
 "Statue [1908]": "塑像 [1908]",
 "Statue": "塑像",
 "Statues": "塑像群",
 "Sunday School": "主日学",
 "Sunday School Scholar (Child)": "主日学学生（孩童）",
 "Sunday School Boys & Braziers": "主日学男童与火盆",
 "Beggar Woman": "女乞丐",
 "Drying Incense": "晾晒香",
 "Entrance College Graduation": "学院毕业典礼·入口",
 "Sidney Gamble outside Gamble Hall": "甘博立于 Gamble Hall 外",
 "City Hill": "城中山丘",
 "Big Street": "大街",
 "Great Street": "大街",
 "View over Roofs": "屋顶上望",
 "Athletes on City Hill": "城中山丘上的运动员",
 "Mud Slide": "泥滑道",
 "Boat on Mud Slide": "泥滑道上的船",
 "Mud Slide  (Palor) top": "泥滑道（Palor）顶端",
 "three-arch Bridge Konztu Chiao": "三孔桥·Konztu Chiao",
 "Child - Silver Ring & Wire Utensil": "孩童·银环与铁丝器具",
 "Rowing Boat": "划船",
 "Bamboo Rafts": "竹筏",
 "Hangzhou Bridge": "杭州的桥",
 "Grave": "墓",
 "Leifeng Pagoda across water": "水对岸的雷峰塔",
 "Leifeng Pagoda and man": "雷峰塔与男子",
 "Leifeng Pagoda": "雷峰塔",
 "Thunder Peak Pagoda": "雷峰塔",
 "three Lamas - Island View": "三名喇嘛·岛景",
 "Official Chair": "官轿",
 "Buffalo Head Water": "水中的水牛头",
 "Ya Ven Gateway": "衙门牌楼",
 "Ya Ven Gate": "衙门",
 "Ya Ven Figures": "衙门塑像",
 "Servant Va Ven (Poor)": "仆人 Va Ven（贫）",
 "Water Chestnuts": "菱角",
 "Imperial Island Bridge": "御岛之桥",
 "Gateway Emperors Island": "御岛门楼",
 "J.H. Arthur": "J.H. Arthur",
 "Tired laborer": "疲惫的劳工",
 "Station Courtyard": "车站庭院",
 "Lin Yin Reader": "灵隐诵经人",
 "Lin Yin Priest": "灵隐僧人",
 "Lin Yin Bridge": "灵隐桥",
 "Linyin Bridge": "灵隐桥",
 "Taiping Graves": "太平军墓",
 "Memorial Services Bridge": "祭礼·桥",
 "Memorial Services Portrait": "祭礼·遗像",
 "Tien Tsoh & Valley": "Tien Tsoh 与山谷",
 "Tien Tsoh Roof": "Tien Tsoh 屋顶",
 "Tien Tsoh Liang Teng": "Tien Tsoh 凉亭",
 "Alice Fitch": "Alice Fitch",
 "Man Saying Charm": "念咒的男子",
 "Taoist Priest (Horizontal)": "道士（横幅）",
 "Taoist Priests (Vertical)": "道士（竖幅）",
 "Incense Burner": "香炉",
 "Fuxing Temple Incense Burner": "复兴寺香炉",
 "Boat & Water Gate": "船与水门",
 "Fortune Teller Near City Gate": "城门边的算命人",
 "Lai Fung Tah Laige": "雷峰塔·Laige",
 "Lai Fung Tah & Liang Tin": "雷峰塔与凉亭",
 "Buddhas Cave Exterior": "佛窟外景",
 "Buddhas Cave Interior": "佛窟内景",
 "Hillside Graves": "山坡上的坟墓",
 "Laughing Buddha": "笑佛",
 "Laughing Buddha & Hidden Self": "笑佛与 Hidden Self",
 "Ape Buddha": "猿猴佛像",
 "City Gate": "城门",
 "Liang Ting - Hills": "凉亭·山",
 "Six Harmonies Pagoda Telar": "六和塔·Telar",
 "Six Harmonies Pagoda Water": "六和塔与水面",
 "Liuhe Pagoda": "六和塔",
 "Dr. Main in Donkey Cart": "Dr. Main 乘驴车",
 "Bridge of Boats": "浮桥",
 "Buffalo Cart": "牛车",
 "Gamble Hall": "Gamble Hall",
 "Chopping Tiger with Old Man": "劈虎（与老者）",
 "Chopping Tiger's Old Man": "劈虎处的老者",
 "Eastern Hell": "东方地狱",
 "Horse & Cow Guardians": "牛头马面",
 "Gate Guards": "门神",
 "Kings of Hell": "阎王",
 "Bell & Clothes": "钟与衣物",
 "Jesuit Urns": "耶稣会士墓瓮",
 "Jesuit Tomb": "耶稣会士墓",
 "Needle Pagoda": "针塔（保俶塔）",
 "Paidle Pagoda & Bridge": "Paidle 塔与桥",
 "Paidle Pagoda & Bridge close": "Paidle 塔与桥（近景）",
 "Fortune Teller Table": "算命摊",
 "Fortune Teller & Stick": "算命人与签",
 "Fortune Teller close": "算命人（近景）",
 "Fortune Teller": "算命人",
 "Mist & Lightning Gods": "雾神与电神",
 "Bloody Pool": "血池",
 "Baby in Barrel": "桶中婴孩",
 "Boat": "船",
 "waterfront": "水边",
 "College from Pagoda": "自塔上望学院",
 "Pagoda from Shore": "自岸边望塔",
 "College from Water": "自水上望学院",
 "Children Carrying Firewood": "背柴的孩童",
 "YMCA Gateway": "青年会门楼",
 "YMCA House": "青年会房舍",
 "YMCA Building": "青年会楼",
 "YMCA, Old Quarters": "青年会旧址",
 "Group Photo, G. Sherwood Eddy, Weigel, others": "群像：G. Sherwood Eddy、Weigel 等",
 "Boat on Qiantang River": "钱塘江上的船",
 "Qiantang River": "钱塘江",
 "Qiantang Gate": "钱塘门",
 "Tucker Chapel": "Tucker 礼拜堂",
 "R W Wheeler": "R W Wheeler",
 "Tomb O-Mi-Do-Va": "O-Mi-Do-Va 墓",
 "Pilgrims": "朝山者",
 "Urns": "瓮",
 "Bird Market": "鸟市",
 "Wood Shop": "木工铺",
 "Junk": "帆船",
 "Gamble Field to River": "Gamble Field 望江",
 "Gamble Field to Hill": "Gamble Field 望山",
 "Making Baskets": "编竹篮",
 "Wood Market and Canal": "木材市场与运河",
 "Hot Water Kettle": "热水壶",
 "Hot Water Kettle close": "热水壶（近景）",
 "Pounding Metal Sheets": "锤打金属片",
 "Girl & Hair": "女孩与发辫",
 "Man Eating Rice": "吃饭的男子",
 "Pusiang Boys": "Pusiang 男童",
 "Pusiang Girls": "Pusiang 女童",
 "Pusiang Children at Table": "Pusiang 孩童围桌",
 "Lathe": "车床",
 "Drill": "钻具",
 "Umbrella Making": "制伞",
 "Pounding Paper": "捶纸",
 "Drum Stretching": "绷鼓面",
 "Carving": "雕刻",
 "Lantern Making": "制灯笼",
 "Bed Weaving": "编床",
 "Bridge - Silk School": "桥·蚕丝学堂",
 "Dyed Cloth": "染布",
 "Drying Dyed Cloth": "晾晒染布",
 "Paper Money": "纸钱",
 "Silkworms": "蚕",
 "Boat & Canopy": "船与船篷",
 "Bamboo Road": "堆着竹子的路",
 "Duckery": "鸭场",
 "Bridge, vertical (Towing Rope)": "桥（竖幅，纤绳）",
 "Bridge, horizontal, with washing on banks": "桥（横幅，岸边洗衣）",
 "Laborers Working": "劳作的工人",
 "Foot Boat & Trees": "脚划船与树",
 "Foot Boat  Across Plates": "脚划船·Across Plates",
 "Foot Boat Stern": "脚划船船尾",
 "Garbage  Boat": "垃圾船",
 "Man & Earring": "男子与耳环",
 "Children with Candy": "拿糖的孩童",
 "Weaving Belts": "编织带子",
 "Silk Loom": "丝织机",
 "Beggar Matting Skirt": "穿草席裙的乞丐",
 "Street Shrine": "街边神龛",
 "Panorama": "全景",
 "Dog on Ceiling": "天花板上的狗",
 "Boat on Lake": "湖上的船",
 "Lake Boat": "湖船",
 "Mr & Mrs R.F. Fitch": "R.F. Fitch 夫妇",
 "Buffalo & Fuel Cart": "水牛与柴车",
 "Buffalo in Water": "水中的水牛",
 "Salt Boat & Wagon": "盐船与盐车",
 "Salt Boat & Wagon Salt Running": "盐船与盐车·卸盐",
 "Salt Brine Wagon": "盐卤车",
 "Red Light Houses": "红灯区房屋",
 "Red Light Houses End": "红灯区房屋（尽头）",
 "Scissors Maker": "制剪匠",
 "Walking Restaurant (street vendor)": "流动饭摊（街头小贩）",
 "Cook Shop": "熟食铺",
 "Woman Praying": "祈祷的妇人",
 "Paper Prayer": "纸符",
 "Girl Eating": "吃东西的女孩",
 "Robert Fitch Residence": "Robert Fitch 宅",
 "Lake Views Telar Pagoda West": "湖景·Telar 塔·西",
 "Lake View  Small": "湖景（小）",
 "River Boat": "江船",
 "Hardown's Garden": "Hardown 花园",
 "Stewart Memorial": "Stewart 纪念堂",
 "Tailor City Street": "裁缝·城中街道",
 "Tea House & Lake": "茶楼与湖",
 "Pilgrim Baskets": "朝山者的篮",
 "Man Smoking": "吸烟的男子",
 "Burning Incense": "焚香",
 "Cutting Wood": "锯木",
 "Two Boats": "两只船",
 "Timber Raft": "木排",
 "Betty in Chair": "Betty 坐在椅中",
 "Tree Reflection": "树影倒映",
 "Men Carrying Fish in Baskets": "挑鱼篮的男子",
 "Women Pilgrims on street": "街上的女朝山者",
 "Pilgrim on Temple steps": "寺庙台阶上的朝山者",
 "Hangzhou city bird's eye view, Leifeng Pagoda in distance": "杭州城鸟瞰，远处雷峰塔",
 "Hangzhou city bird's eye view": "杭州城鸟瞰",
 "Houses on a hill": "山上的房屋",
 "House on the hill": "山上的房屋",
 "Western Family": "西方一家人",
 "Western lady on a sedan chair": "乘轿的西方女子",
 "David B. Gamble standing next to a sedan chair": "David B. Gamble 立于轿旁",
 "David Gamble sitting inside a sedan chair": "David Gamble 坐在轿中",
 "A group of Chinese men eating around a table": "一群中国男子围桌用餐",
 "Chinese man portrait": "中国男子像",
 "People walking alongside a street": "沿街行走的人",
 "Small boat on the water": "水上小船",
 "Hut by the river with a few small boats in the front": "河边小屋与几只小船",
 "Field": "田地",
 "Pai fang": "牌坊",
 "Two Western Women in Sedan Chairs, Leifeng Pagoda in the background": "两名西方女子乘轿，背景为雷峰塔",
 "Boats on lake shore": "湖岸的船",
 "Visitors near a gate": "门边的游人",
 "A group of curious Chinese around Gamble": "围看甘博的中国人",
 "People in front of a food stand": "食摊前的人群",
 "Wood work": "木工",
 "David Gamble, Sidney Gamble and Clarence Gamble taking photographs on street":
   "David、Sidney、Clarence Gamble 在街头拍照",
 "Cotton shop": "棉花店",
 "Chinese lady holding one child with another one standing by her": "抱着孩子的中国妇人，旁立另一孩童",
 "People standing in front of houses on a street": "站在街边房屋前的人们",
 "Chinese couple": "中国夫妇",
 "Budda statue in a temple": "寺庙中的佛像",
 "Monks on the steps of a temple building": "寺庙台阶上的僧人",
 "Making clay sculptures": "制泥塑",
 "Visitors in sedan chairs and their carriers resting in the field": "乘轿的游人与歇息的轿夫",
 "Tomb of Yue Fei": "岳飞墓",
 "Kneeling statues of sinners": "跪着的罪人塑像",
 "Houses and trees on the bank": "岸边的房屋与树",
 "Shaded mountain road": "林荫山路",
 "Soldiers with flag near Qingtai gate": "清泰门附近的持旗士兵",
 "Closeup of soldiers": "士兵近景",
 "Baffalos on the shore & next to city wall": "岸边城墙下的水牛",
 "Street market": "街市",
}

CN = "一二三四五六七八九十"


def zh_num(i):
    return CN[i - 1] if i <= 10 else str(i)


todo = json.load(open(f"{S}/hz_todo.json"))
out, missing = {}, []
for path, title in todo:
    if "Untitled lantern slide" in title:
        key = path.split("_LS_")[1][:4]
        zh = UNTITLED.get(key)
        if not zh:
            missing.append((path, title))
            continue
    else:
        zh = T.get(title.strip()) or T.get(title)
        if not zh:
            missing.append((path, title))
            continue
    out[path] = zh

# 同名去重编号
groups = collections.defaultdict(list)
for p, z in out.items():
    groups[z].append(p)
for z, paths in groups.items():
    if len(paths) > 1 and "无题" not in z and len(z) <= 10:
        for i, p in enumerate(sorted(paths), 1):
            out[p] = f"{z} 之{zh_num(i)}"

print("已译:", len(out), "| 未覆盖:", len(missing))
for p, t in missing:
    print("  MISS:", t, "|", p)

# 合并进现有映射
f = f"{BASE}/tools/titles_zh.json"
cur = json.load(open(f))
cur.update(out)
comment = cur.pop("_comment")
merged = {"_comment": comment, **dict(sorted(cur.items()))}
json.dump(merged, open(f, "w"), ensure_ascii=False, indent=1)
print("titles_zh.json 总条目:", len(merged) - 1)
